using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;


namespace FacturaElectronica.CFDI33.Complementos.Nomina12
{
    

    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")]
    public enum c_Estado
    {
        [System.Xml.Serialization.XmlEnumAttribute("AGU")]
        [StringValue("AGU")]
        AGU,
        [System.Xml.Serialization.XmlEnumAttribute("BCN")]
        [StringValue("BCN")]
        BCN,
        [System.Xml.Serialization.XmlEnumAttribute("BCS")]
        [StringValue("BCS")]
        BCS,
        [System.Xml.Serialization.XmlEnumAttribute("CAM")]
        [StringValue("CAM")]
        CAM,
        [System.Xml.Serialization.XmlEnumAttribute("CHP")]
        [StringValue("CHP")]
        CHP,
        [System.Xml.Serialization.XmlEnumAttribute("CHH")]
        [StringValue("CHH")]
        CHH,
        [System.Xml.Serialization.XmlEnumAttribute("COA")]
        [StringValue("COA")]
        COA,
        [System.Xml.Serialization.XmlEnumAttribute("COL")]
        [StringValue("COL")]
        COL,
        [System.Xml.Serialization.XmlEnumAttribute("DIF")]
        [StringValue("DIF")]
        DIF,
        [System.Xml.Serialization.XmlEnumAttribute("DUR")]
        [StringValue("DUR")]
        DUR,
        [System.Xml.Serialization.XmlEnumAttribute("GUA")]
        [StringValue("GUA")]
        GUA,
        [System.Xml.Serialization.XmlEnumAttribute("GRO")]
        [StringValue("GRO")]
        GRO,
        [System.Xml.Serialization.XmlEnumAttribute("HID")]
        [StringValue("HID")]
        HID,
        [System.Xml.Serialization.XmlEnumAttribute("JAL")]
        [StringValue("JAL")]
        JAL,
        [System.Xml.Serialization.XmlEnumAttribute("MEX")]
        [StringValue("MEX")]
        MEX,
        [System.Xml.Serialization.XmlEnumAttribute("MIC")]
        [StringValue("MIC")]
        MIC,
        [System.Xml.Serialization.XmlEnumAttribute("MOR")]
        [StringValue("MOR")]
        MOR,
        [System.Xml.Serialization.XmlEnumAttribute("NAY")]
        [StringValue("NAY")]
        NAY,
        [System.Xml.Serialization.XmlEnumAttribute("NLE")]
        [StringValue("NLE")]
        NLE,
        [System.Xml.Serialization.XmlEnumAttribute("OAX")]
        [StringValue("OAX")]
        OAX,
        [System.Xml.Serialization.XmlEnumAttribute("PUE")]
        [StringValue("PUE")]
        PUE,
        [System.Xml.Serialization.XmlEnumAttribute("QUE")]
        [StringValue("QUE")]
        QUE,
        [System.Xml.Serialization.XmlEnumAttribute("ROO")]
        [StringValue("ROO")]
        ROO,
        [System.Xml.Serialization.XmlEnumAttribute("SLP")]
        [StringValue("SLP")]
        SLP,
        [System.Xml.Serialization.XmlEnumAttribute("SIN")]
        [StringValue("SIN")]
        SIN,
        [System.Xml.Serialization.XmlEnumAttribute("SON")]
        [StringValue("SON")]
        SON,
        [System.Xml.Serialization.XmlEnumAttribute("TAB")]
        [StringValue("TAB")]
        TAB,
        [System.Xml.Serialization.XmlEnumAttribute("TAM")]
        [StringValue("TAM")]
        TAM,
        [System.Xml.Serialization.XmlEnumAttribute("TLA")]
        [StringValue("TLA")]
        TLA,
        [System.Xml.Serialization.XmlEnumAttribute("VER")]
        [StringValue("VER")]
        VER,
        [System.Xml.Serialization.XmlEnumAttribute("YUC")]
        [StringValue("YUC")]
        YUC,
        [System.Xml.Serialization.XmlEnumAttribute("ZAC")]
        [StringValue("ZAC")]
        ZAC,
        [System.Xml.Serialization.XmlEnumAttribute("AL")]
        [StringValue("AL")]
        AL,
        [System.Xml.Serialization.XmlEnumAttribute("AK")]
        [StringValue("AK")]
        AK,
        [System.Xml.Serialization.XmlEnumAttribute("AZ")]
        [StringValue("AZ")]
        AZ,
        [System.Xml.Serialization.XmlEnumAttribute("AR")]
        [StringValue("AR")]
        AR,
        [System.Xml.Serialization.XmlEnumAttribute("CA")]
        [StringValue("CA")]
        CA,
        [System.Xml.Serialization.XmlEnumAttribute("NC")]
        [StringValue("NC")]
        NC,
        [System.Xml.Serialization.XmlEnumAttribute("SC")]
        [StringValue("SC")]
        SC,
        [System.Xml.Serialization.XmlEnumAttribute("CO")]
        [StringValue("CO")]
        CO,
        [System.Xml.Serialization.XmlEnumAttribute("CT")]
        [StringValue("CT")]
        CT,
        [System.Xml.Serialization.XmlEnumAttribute("ND")]
        [StringValue("ND")]
        ND,
        [System.Xml.Serialization.XmlEnumAttribute("SD")]
        [StringValue("SD")]
        SD,
        [System.Xml.Serialization.XmlEnumAttribute("DE")]
        [StringValue("DE")]
        DE,
        [System.Xml.Serialization.XmlEnumAttribute("FL")]
        [StringValue("FL")]
        FL,
        [System.Xml.Serialization.XmlEnumAttribute("GA")]
        [StringValue("GA")]
        GA,
        [System.Xml.Serialization.XmlEnumAttribute("HI")]
        [StringValue("HI")]
        HI,
        [System.Xml.Serialization.XmlEnumAttribute("ID")]
        [StringValue("ID")]
        ID,
        [System.Xml.Serialization.XmlEnumAttribute("IL")]
        [StringValue("IL")]
        IL,
        [System.Xml.Serialization.XmlEnumAttribute("IN")]
        [StringValue("IN")]
        IN,
        [System.Xml.Serialization.XmlEnumAttribute("IA")]
        [StringValue("IA")]
        IA,
        [System.Xml.Serialization.XmlEnumAttribute("KS")]
        [StringValue("KS")]
        KS,
        [System.Xml.Serialization.XmlEnumAttribute("KY")]
        [StringValue("KY")]
        KY,
        [System.Xml.Serialization.XmlEnumAttribute("LA")]
        [StringValue("LA")]
        LA,
        [System.Xml.Serialization.XmlEnumAttribute("ME")]
        [StringValue("ME")]
        ME,
        [System.Xml.Serialization.XmlEnumAttribute("MD")]
        [StringValue("MD")]
        MD,
        [System.Xml.Serialization.XmlEnumAttribute("MA")]
        [StringValue("MA")]
        MA,
        [System.Xml.Serialization.XmlEnumAttribute("MI")]
        [StringValue("MI")]
        MI,
        [System.Xml.Serialization.XmlEnumAttribute("MN")]
        [StringValue("MN")]
        MN,
        [System.Xml.Serialization.XmlEnumAttribute("MS")]
        [StringValue("MS")]
        MS,
        [System.Xml.Serialization.XmlEnumAttribute("MO")]
        [StringValue("MO")]
        MO,
        [System.Xml.Serialization.XmlEnumAttribute("MT")]
        [StringValue("MT")]
        MT,
        [System.Xml.Serialization.XmlEnumAttribute("NE")]
        [StringValue("NE")]
        NE,
        [System.Xml.Serialization.XmlEnumAttribute("NV")]
        [StringValue("NV")]
        NV,
        [System.Xml.Serialization.XmlEnumAttribute("NJ")]
        [StringValue("NJ")]
        NJ,
        [System.Xml.Serialization.XmlEnumAttribute("NY")]
        [StringValue("NY")]
        NY,
        [System.Xml.Serialization.XmlEnumAttribute("NH")]
        [StringValue("NH")]
        NH,
        [System.Xml.Serialization.XmlEnumAttribute("NM")]
        [StringValue("NM")]
        NM,
        [System.Xml.Serialization.XmlEnumAttribute("OH")]
        [StringValue("OH")]
        OH,
        [System.Xml.Serialization.XmlEnumAttribute("OK")]
        [StringValue("OK")]
        OK,
        [System.Xml.Serialization.XmlEnumAttribute("OR")]
        [StringValue("OR")]
        OR,
        [System.Xml.Serialization.XmlEnumAttribute("PA")]
        [StringValue("PA")]
        PA,
        [System.Xml.Serialization.XmlEnumAttribute("RI")]
        [StringValue("RI")]
        RI,
        [System.Xml.Serialization.XmlEnumAttribute("TN")]
        [StringValue("TN")]
        TN,
        [System.Xml.Serialization.XmlEnumAttribute("TX")]
        [StringValue("TX")]
        TX,
        [System.Xml.Serialization.XmlEnumAttribute("UT")]
        [StringValue("UT")]
        UT,
        [System.Xml.Serialization.XmlEnumAttribute("VT")]
        [StringValue("VT")]
        VT,
        [System.Xml.Serialization.XmlEnumAttribute("VA")]
        [StringValue("VA")]
        VA,
        [System.Xml.Serialization.XmlEnumAttribute("WV")]
        [StringValue("WV")]
        WV,
        [System.Xml.Serialization.XmlEnumAttribute("WA")]
        [StringValue("WA")]
        WA,
        [System.Xml.Serialization.XmlEnumAttribute("WI")]
        [StringValue("WI")]
        WI,
        [System.Xml.Serialization.XmlEnumAttribute("WY")]
        [StringValue("WY")]
        WY,
        [System.Xml.Serialization.XmlEnumAttribute("ON")]
        [StringValue("ON")]
        ON,
        [System.Xml.Serialization.XmlEnumAttribute("QC")]
        [StringValue("QC")]
        QC,
        [System.Xml.Serialization.XmlEnumAttribute("NS")]
        [StringValue("NS")]
        NS,
        [System.Xml.Serialization.XmlEnumAttribute("NB")]
        [StringValue("NB")]
        NB,
        [System.Xml.Serialization.XmlEnumAttribute("MB")]
        [StringValue("MB")]
        MB,
        [System.Xml.Serialization.XmlEnumAttribute("BC")]
        [StringValue("BC")]
        BC,
        [System.Xml.Serialization.XmlEnumAttribute("PE")]
        [StringValue("PE")]
        PE,
        [System.Xml.Serialization.XmlEnumAttribute("SK")]
        [StringValue("SK")]
        SK,
        [System.Xml.Serialization.XmlEnumAttribute("AB")]
        [StringValue("AB")]
        AB,
        [System.Xml.Serialization.XmlEnumAttribute("NL")]
        [StringValue("NL")]
        NL,
        [System.Xml.Serialization.XmlEnumAttribute("NT")]
        [StringValue("NT")]
        NT,
        [System.Xml.Serialization.XmlEnumAttribute("YT")]
        [StringValue("YT")]
        YT,
        [System.Xml.Serialization.XmlEnumAttribute("UN")]
        [StringValue("UN")]
        UN,
    }
}

