using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FacturaElectronica.CFDI33
{
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")]
    public enum c_Moneda
    {

        [StringValue("AED")]
        AED,
        [StringValue("AFN")]
        AFN,
        [StringValue("ALL")]
        ALL,
        [StringValue("AMD")]
        AMD,
        [StringValue("ANG")]
        ANG,
        [StringValue("AOA")]
        AOA,
        [StringValue("ARS")]
        ARS,
        [StringValue("AUD")]
        AUD,
        [StringValue("AWG")]
        AWG,
        [StringValue("AZN")]
        AZN,
        [StringValue("BAM")]
        BAM,
        [StringValue("BBD")]
        BBD,
        [StringValue("BDT")]
        BDT,
        [StringValue("BGN")]
        BGN,
        [StringValue("BHD")]
        BHD,
        [StringValue("BIF")]
        BIF,
        [StringValue("BMD")]
        BMD,
        [StringValue("BND")]
        BND,
        [StringValue("BOB")]
        BOB,
        [StringValue("BOV")]
        BOV,
        [StringValue("BRL")]
        BRL,
        [StringValue("BSD")]
        BSD,
        [StringValue("BTN")]
        BTN,
        [StringValue("BWP")]
        BWP,
        [StringValue("BYR")]
        BYR,
        [StringValue("BZD")]
        BZD,
        [StringValue("CAD")]
        CAD,
        [StringValue("CDF")]
        CDF,
        [StringValue("CHE")]
        CHE,
        [StringValue("CHF")]
        CHF,
        [StringValue("CHW")]
        CHW,
        [StringValue("CLF")]
        CLF,
        [StringValue("CLP")]
        CLP,
        [StringValue("CNY")]
        CNY,
        [StringValue("COP")]
        COP,
        [StringValue("COU")]
        COU,
        [StringValue("CRC")]
        CRC,
        [StringValue("CUC")]
        CUC,
        [StringValue("CUP")]
        CUP,
        [StringValue("CVE")]
        CVE,
        [StringValue("CZK")]
        CZK,
        [StringValue("DJF")]
        DJF,
        [StringValue("DKK")]
        DKK,
        [StringValue("DOP")]
        DOP,
        [StringValue("DZD")]
        DZD,
        [StringValue("EGP")]
        EGP,
        [StringValue("ERN")]
        ERN,
        [StringValue("ETB")]
        ETB,
        [StringValue("EUR")]
        EUR,
        [StringValue("FJD")]
        FJD,
        [StringValue("FKP")]
        FKP,
        [StringValue("GBP")]
        GBP,
        [StringValue("GEL")]
        GEL,
        [StringValue("GHS")]
        GHS,
        [StringValue("GIP")]
        GIP,
        [StringValue("GMD")]
        GMD,
        [StringValue("GNF")]
        GNF,
        [StringValue("GTQ")]
        GTQ,
        [StringValue("GYD")]
        GYD,
        [StringValue("HKD")]
        HKD,
        [StringValue("HNL")]
        HNL,
        [StringValue("HRK")]
        HRK,
        [StringValue("HTG")]
        HTG,
        [StringValue("HUF")]
        HUF,
        [StringValue("IDR")]
        IDR,
        [StringValue("ILS")]
        ILS,
        [StringValue("INR")]
        INR,
        [StringValue("IQD")]
        IQD,
        [StringValue("IRR")]
        IRR,
        [StringValue("ISK")]
        ISK,
        [StringValue("JMD")]
        JMD,
        [StringValue("JOD")]
        JOD,
        [StringValue("JPY")]
        JPY,
        [StringValue("KES")]
        KES,
        [StringValue("KGS")]
        KGS,
        [StringValue("KHR")]
        KHR,
        [StringValue("KMF")]
        KMF,
        [StringValue("KPW")]
        KPW,
        [StringValue("KRW")]
        KRW,
        [StringValue("KWD")]
        KWD,
        [StringValue("KYD")]
        KYD,
        [StringValue("KZT")]
        KZT,
        [StringValue("LAK")]
        LAK,
        [StringValue("LBP")]
        LBP,
        [StringValue("LKR")]
        LKR,
        [StringValue("LRD")]
        LRD,
        [StringValue("LSL")]
        LSL,
        [StringValue("LYD")]
        LYD,
        [StringValue("MAD")]
        MAD,
        [StringValue("MDL")]
        MDL,
        [StringValue("MGA")]
        MGA,
        [StringValue("MKD")]
        MKD,
        [StringValue("MMK")]
        MMK,
        [StringValue("MNT")]
        MNT,
        [StringValue("MOP")]
        MOP,
        [StringValue("MRO")]
        MRO,
        [StringValue("MUR")]
        MUR,
        [StringValue("MVR")]
        MVR,
        [StringValue("MWK")]
        MWK,
        [StringValue("MXN")]
        MXN,
        [StringValue("MXV")]
        MXV,
        [StringValue("MYR")]
        MYR,
        [StringValue("MZN")]
        MZN,
        [StringValue("NAD")]
        NAD,
        [StringValue("NGN")]
        NGN,
        [StringValue("NIO")]
        NIO,
        [StringValue("NOK")]
        NOK,
        [StringValue("NPR")]
        NPR,
        [StringValue("NZD")]
        NZD,
        [StringValue("OMR")]
        OMR,
        [StringValue("PAB")]
        PAB,
        [StringValue("PEN")]
        PEN,
        [StringValue("PGK")]
        PGK,
        [StringValue("PHP")]
        PHP,
        [StringValue("PKR")]
        PKR,
        [StringValue("PLN")]
        PLN,
        [StringValue("PYG")]
        PYG,
        [StringValue("QAR")]
        QAR,
        [StringValue("RON")]
        RON,
        [StringValue("RSD")]
        RSD,
        [StringValue("RUB")]
        RUB,
        [StringValue("RWF")]
        RWF,
        [StringValue("SAR")]
        SAR,
        [StringValue("SBD")]
        SBD,
        [StringValue("SCR")]
        SCR,
        [StringValue("SDG")]
        SDG,
        [StringValue("SEK")]
        SEK,
        [StringValue("SGD")]
        SGD,
        [StringValue("SHP")]
        SHP,
        [StringValue("SLL")]
        SLL,
        [StringValue("SOS")]
        SOS,
        [StringValue("SRD")]
        SRD,
        [StringValue("SSP")]
        SSP,
        [StringValue("STD")]
        STD,
        [StringValue("SVC")]
        SVC,
        [StringValue("SYP")]
        SYP,
        [StringValue("SZL")]
        SZL,
        [StringValue("THB")]
        THB,
        [StringValue("TJS")]
        TJS,
        [StringValue("TMT")]
        TMT,
        [StringValue("TND")]
        TND,
        [StringValue("TOP")]
        TOP,
        [StringValue("TRY")]
        TRY,
        [StringValue("TTD")]
        TTD,
        [StringValue("TWD")]
        TWD,
        [StringValue("TZS")]
        TZS,
        [StringValue("UAH")]
        UAH,
        [StringValue("UGX")]
        UGX,
        [StringValue("USD")]
        USD,
        [StringValue("USN")]
        USN,
        [StringValue("UYI")]
        UYI,
        [StringValue("UYU")]
        UYU,
        [StringValue("UZS")]
        UZS,
        [StringValue("VEF")]
        VEF,
        [StringValue("VND")]
        VND,
        [StringValue("VUV")]
        VUV,
        [StringValue("WST")]
        WST,
        [StringValue("XAF")]
        XAF,
        [StringValue("XAG")]
        XAG,
        [StringValue("XAU")]
        XAU,
        [StringValue("XBA")]
        XBA,
        [StringValue("XBB")]
        XBB,
        [StringValue("XBC")]
        XBC,
        [StringValue("XBD")]
        XBD,
        [StringValue("XCD")]
        XCD,
        [StringValue("XDR")]
        XDR,
        [StringValue("XOF")]
        XOF,
        [StringValue("XPD")]
        XPD,
        [StringValue("XPF")]
        XPF,
        [StringValue("XPT")]
        XPT,
        [StringValue("XSU")]
        XSU,
        [StringValue("XTS")]
        XTS,
        [StringValue("XUA")]
        XUA,
        [StringValue("XXX")]
        XXX,
        [StringValue("YER")]
        YER,
        [StringValue("ZAR")]
        ZAR,
        [StringValue("ZMW")]
        ZMW,
        [StringValue("ZWL")]
        ZWL
    }

    
}
