using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

namespace FacturaElectronica.CFDI33
{
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")]
    public enum c_Pais
    {
        [StringValue("AFG")]
        AFG,
        [StringValue("ALA")]
        ALA,
        [StringValue("ALB")]
        ALB,
        [StringValue("DEU")]
        DEU,
        [StringValue("AND")]
        AND,
        [StringValue("AGO")]
        AGO,
        [StringValue("AIA")]
        AIA,
        [StringValue("ATA")]
        ATA,
        [StringValue("ATG")]
        ATG,
        [StringValue("SAU")]
        SAU,
        [StringValue("DZA")]
        DZA,
        [StringValue("ARG")]
        ARG,
        [StringValue("ARM")]
        ARM,
        [StringValue("ABW")]
        ABW,
        [StringValue("AUS")]
        AUS,
        [StringValue("AUT")]
        AUT,
        [StringValue("AZE")]
        AZE,
        [StringValue("BHS")]
        BHS,
        [StringValue("BGD")]
        BGD,
        [StringValue("BRB")]
        BRB,
        [StringValue("BHR")]
        BHR,
        [StringValue("BEL")]
        BEL,
        [StringValue("BLZ")]
        BLZ,
        [StringValue("BEN")]
        BEN,
        [StringValue("BMU")]
        BMU,
        [StringValue("BLR")]
        BLR,
        [StringValue("MMR")]
        MMR,
        [StringValue("BOL")]
        BOL,
        [StringValue("BIH")]
        BIH,
        [StringValue("BWA")]
        BWA,
        [StringValue("BRA")]
        BRA,
        [StringValue("BRN")]
        BRN,
        [StringValue("BGR")]
        BGR,
        [StringValue("BFA")]
        BFA,
        [StringValue("BDI")]
        BDI,
        [StringValue("BTN")]
        BTN,
        [StringValue("CPV")]
        CPV,
        [StringValue("KHM")]
        KHM,
        [StringValue("CMR")]
        CMR,
        [StringValue("CAN")]
        CAN,
        [StringValue("QAT")]
        QAT,
        [StringValue("BES")]
        BES,
        [StringValue("TCD")]
        TCD,
        [StringValue("CHL")]
        CHL,
        [StringValue("CHN")]
        CHN,
        [StringValue("CYP")]
        CYP,
        [StringValue("COL")]
        COL,
        [StringValue("COM")]
        COM,
        [StringValue("PRK")]
        PRK,
        [StringValue("KOR")]
        KOR,
        [StringValue("CIV")]
        CIV,
        [StringValue("CRI")]
        CRI,
        [StringValue("HRV")]
        HRV,
        [StringValue("CUB")]
        CUB,
        [StringValue("CUW")]
        CUW,
        [StringValue("DNK")]
        DNK,
        [StringValue("DMA")]
        DMA,
        [StringValue("ECU")]
        ECU,
        [StringValue("EGY")]
        EGY,
        [StringValue("SLV")]
        SLV,
        [StringValue("ARE")]
        ARE,
        [StringValue("ERI")]
        ERI,
        [StringValue("SVK")]
        SVK,
        [StringValue("SVN")]
        SVN,
        [StringValue("ESP")]
        ESP,
        [StringValue("USA")]
        USA,
        [StringValue("EST")]
        EST,
        [StringValue("ETH")]
        ETH,
        [StringValue("PHL")]
        PHL,
        [StringValue("FIN")]
        FIN,
        [StringValue("FJI")]
        FJI,
        [StringValue("FRA")]
        FRA,
        [StringValue("GAB")]
        GAB,
        [StringValue("GMB")]
        GMB,
        [StringValue("GEO")]
        GEO,
        [StringValue("GHA")]
        GHA,
        [StringValue("GIB")]
        GIB,
        [StringValue("GRD")]
        GRD,
        [StringValue("GRC")]
        GRC,
        [StringValue("GRL")]
        GRL,
        [StringValue("GLP")]
        GLP,
        [StringValue("GUM")]
        GUM,
        [StringValue("GTM")]
        GTM,
        [StringValue("GUF")]
        GUF,
        [StringValue("GGY")]
        GGY,
        [StringValue("GIN")]
        GIN,
        [StringValue("GNB")]
        GNB,
        [StringValue("GNQ")]
        GNQ,
        [StringValue("GUY")]
        GUY,
        [StringValue("HTI")]
        HTI,
        [StringValue("HND")]
        HND,
        [StringValue("HKG")]
        HKG,
        [StringValue("HUN")]
        HUN,
        [StringValue("IND")]
        IND,
        [StringValue("IDN")]
        IDN,
        [StringValue("IRQ")]
        IRQ,
        [StringValue("IRN")]
        IRN,
        [StringValue("IRL")]
        IRL,
        [StringValue("BVT")]
        BVT,
        [StringValue("IMN")]
        IMN,
        [StringValue("CXR")]
        CXR,
        [StringValue("NFK")]
        NFK,
        [StringValue("ISL")]
        ISL,
        [StringValue("CYM")]
        CYM,
        [StringValue("CCK")]
        CCK,
        [StringValue("COK")]
        COK,
        [StringValue("FRO")]
        FRO,
        [StringValue("SGS")]
        SGS,
        [StringValue("HMD")]
        HMD,
        [StringValue("FLK")]
        FLK,
        [StringValue("MNP")]
        MNP,
        [StringValue("MHL")]
        MHL,
        [StringValue("PCN")]
        PCN,
        [StringValue("SLB")]
        SLB,
        [StringValue("TCA")]
        TCA,
        [StringValue("UMI")]
        UMI,
        [StringValue("VGB")]
        VGB,
        [StringValue("VIR")]
        VIR,
        [StringValue("ISR")]
        ISR,
        [StringValue("ITA")]
        ITA,
        [StringValue("JAM")]
        JAM,
        [StringValue("JPN")]
        JPN,
        [StringValue("JEY")]
        JEY,
        [StringValue("JOR")]
        JOR,
        [StringValue("KAZ")]
        KAZ,
        [StringValue("KEN")]
        KEN,
        [StringValue("KGZ")]
        KGZ,
        [StringValue("KIR")]
        KIR,
        [StringValue("KWT")]
        KWT,
        [StringValue("LAO")]
        LAO,
        [StringValue("LSO")]
        LSO,
        [StringValue("LVA")]
        LVA,
        [StringValue("LBN")]
        LBN,
        [StringValue("LBR")]
        LBR,
        [StringValue("LBY")]
        LBY,
        [StringValue("LIE")]
        LIE,
        [StringValue("LTU")]
        LTU,
        [StringValue("LUX")]
        LUX,
        [StringValue("MAC")]
        MAC,
        [StringValue("MDG")]
        MDG,
        [StringValue("MYS")]
        MYS,
        [StringValue("MWI")]
        MWI,
        [StringValue("MDV")]
        MDV,
        [StringValue("MLI")]
        MLI,
        [StringValue("MLT")]
        MLT,
        [StringValue("MAR")]
        MAR,
        [StringValue("MTQ")]
        MTQ,
        [StringValue("MUS")]
        MUS,
        [StringValue("MRT")]
        MRT,
        [StringValue("MYT")]
        MYT,
        [StringValue("MEX")]
        MEX,
        [StringValue("FSM")]
        FSM,
        [StringValue("MDA")]
        MDA,
        [StringValue("MCO")]
        MCO,
        [StringValue("MNG")]
        MNG,
        [StringValue("MNE")]
        MNE,
        [StringValue("MSR")]
        MSR,
        [StringValue("MOZ")]
        MOZ,
        [StringValue("NAM")]
        NAM,
        [StringValue("NRU")]
        NRU,
        [StringValue("NPL")]
        NPL,
        [StringValue("NIC")]
        NIC,
        [StringValue("NER")]
        NER,
        [StringValue("NGA")]
        NGA,
        [StringValue("NIU")]
        NIU,
        [StringValue("NOR")]
        NOR,
        [StringValue("NCL")]
        NCL,
        [StringValue("NZL")]
        NZL,
        [StringValue("OMN")]
        OMN,
        [StringValue("NLD")]
        NLD,
        [StringValue("PAK")]
        PAK,
        [StringValue("PLW")]
        PLW,
        [StringValue("PSE")]
        PSE,
        [StringValue("PAN")]
        PAN,
        [StringValue("PNG")]
        PNG,
        [StringValue("PRY")]
        PRY,
        [StringValue("PER")]
        PER,
        [StringValue("PYF")]
        PYF,
        [StringValue("POL")]
        POL,
        [StringValue("PRT")]
        PRT,
        [StringValue("PRI")]
        PRI,
        [StringValue("GBR")]
        GBR,
        [StringValue("CAF")]
        CAF,
        [StringValue("CZE")]
        CZE,
        [StringValue("MKD")]
        MKD,
        [StringValue("COG")]
        COG,
        [StringValue("COD")]
        COD,
        [StringValue("DOM")]
        DOM,
        [StringValue("REU")]
        REU,
        [StringValue("RWA")]
        RWA,
        [StringValue("ROU")]
        ROU,
        [StringValue("RUS")]
        RUS,
        [StringValue("ESH")]
        ESH,
        [StringValue("WSM")]
        WSM,
        [StringValue("ASM")]
        ASM,
        [StringValue("BLM")]
        BLM,
        [StringValue("KNA")]
        KNA,
        [StringValue("SMR")]
        SMR,
        [StringValue("MAF")]
        MAF,
        [StringValue("SPM")]
        SPM,
        [StringValue("VCT")]
        VCT,
        [StringValue("SHN")]
        SHN,
        [StringValue("LCA")]
        LCA,
        [StringValue("STP")]
        STP,
        [StringValue("SEN")]
        SEN,
        [StringValue("SRB")]
        SRB,
        [StringValue("SYC")]
        SYC,
        [StringValue("SLE")]
        SLE,
        [StringValue("SGP")]
        SGP,
        [StringValue("SXM")]
        SXM,
        [StringValue("SYR")]
        SYR,
        [StringValue("SOM")]
        SOM,
        [StringValue("LKA")]
        LKA,
        [StringValue("SWZ")]
        SWZ,
        [StringValue("ZAF")]
        ZAF,
        [StringValue("SDN")]
        SDN,
        [StringValue("SSD")]
        SSD,
        [StringValue("SWE")]
        SWE,
        [StringValue("CHE")]
        CHE,
        [StringValue("SUR")]
        SUR,
        [StringValue("SJM")]
        SJM,
        [StringValue("THA")]
        THA,
        [StringValue("TWN")]
        TWN,
        [StringValue("TZA")]
        TZA,
        [StringValue("TJK")]
        TJK,
        [StringValue("IOT")]
        IOT,
        [StringValue("ATF")]
        ATF,
        [StringValue("TLS")]
        TLS,
        [StringValue("TGO")]
        TGO,
        [StringValue("TKL")]
        TKL,
        [StringValue("TON")]
        TON,
        [StringValue("TTO")]
        TTO,
        [StringValue("TUN")]
        TUN,
        [StringValue("TKM")]
        TKM,
        [StringValue("TUR")]
        TUR,
        [StringValue("TUV")]
        TUV,
        [StringValue("UKR")]
        UKR,
        [StringValue("UGA")]
        UGA,
        [StringValue("URY")]
        URY,
        [StringValue("UZB")]
        UZB,
        [StringValue("VUT")]
        VUT,
        [StringValue("VAT")]
        VAT,
        [StringValue("VEN")]
        VEN,
        [StringValue("VNM")]
        VNM,
        [StringValue("WLF")]
        WLF,
        [StringValue("YEM")]
        YEM,
        [StringValue("DJI")]
        DJI,
        [StringValue("ZMB")]
        ZMB,
        [StringValue("ZWE")]
        ZWE,
        [StringValue("ZZZ")]
        ZZZ,
    }

}
